name: Docker Image CI

env:
  TAG: 'latest'
  
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:

  build:

    runs-on: ubuntu-latest
    name: Build image
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Log into Docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: _json_key
          password: ${{ env.GCP_CREDENTIALS }}
      - name: Build and push on grandnode2
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args: |
            GIT_COMMIT=${{ github.sha }}
            GIT_BRANCH=${{ github.ref_name }}
          push: true
          platforms: linux/amd64
          tags: grandnode/grandnode2:${{ env.TAG }}
      - name: Build and push on develop
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args: |
            GIT_COMMIT=${{ github.sha }}
            GIT_BRANCH=${{ github.ref_name }}
          push: true
          platforms: linux/amd64
          tags: grandnode/develop:${{ env.TAG }}
